### PR TITLE
migrate to github actions

### PR DESCRIPTION
**Pull request by marbar3778**
this repo needs github actions enabled

### CODE REVIEW

**Review by liamsi — APPROVED** [review]
LGTM, I think @musalbas needs to approve this.

**Comment by musalbas** [comment]
This looks like it broke build and coverage tests?

**Comment by marbar3778** [comment]
> This looks like it broke build and coverage tests?

Not sure how to check, but this would break travisci. The reason I migrated from goveralls to codecov is to be consistent with ll-core. I can put goveralls back if you prefer it.

**Comment by liamsi** [comment]
@musalbas what is the state of this PR? IMO, it would be good if the CI and coverage tools were consistent between repos (if possible). If you want to merge this, I think you only need to [generate a token for codecov](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/disabling-and-enabling-a-workflow) (or Marko needs to change back to goveralls) and check the [actions tab](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/disabling-and-enabling-a-workflow) on the repo.

**Comment by musalbas** [comment]
Before this can merged, we need both build tests and coverage tests working, and the buttons on the readme should be up to date. Let me know what steps on my side would be needed from this. I cannot see any actions in action tab in the repo.

**Comment by marbar3778** [comment]
> Let me know what steps on my side would be needed from this.

Are actions enabled in the settings tab? This should be able to run when not on master

**Comment by musalbas** [comment]
Yes:
image

**Comment by liamsi** [comment]
Action items:
 - [ ] generate a codecov token: https://codecov.io/gh/lazyledger/smt (@musalbas) 
 - [ ] update badges in readme (@marbar3778)
 - [ ] make sure this is actually run (@marbar3778 and @musalbas)

**Comment by musalbas** [comment]
Ok, I've generated a codecov token. Where do I need to add it? As a repository secret?

**Comment by marbar3778** [comment]
Not sure if this has something to do with the branch coming from a fork, but it works in my repo (https://github.com/marbar3778/smt/pull/1). 

No need to post the key anywhere. Its auto generated when using open source last I read

**Comment by liamsi** [comment]
my bad:
image

https://docs.codecov.io/docs/about-the-codecov-bash-uploader#upload-token

**Comment by liamsi** [comment]
If I understand the documentation correctly, it should be the other way around:

**Pull request closed without merging**
